### ISSUE TITLE
Баги

### ISSUE THREAD

**Issue by kate-fsd** [wendivue/range-slider#10]
![Peek 2021-09-17 19-57](https://user-images.githubusercontent.com/66846004/133826099-9ae2fe98-9304-4104-bcb9-64b2f0865582.gif)

**Comment by kate-fsd** [comment]
Обрати внимание на этот пункт https://coda.io/d/MetaLamp_dXh0LxbfZxo/Front-end_su74P#_lu4Cc
При введенных мною данных должны быть шаги 0, 9, 10

**Comment by wendivue** [comment]
> Обрати внимание на этот пункт https://coda.io/d/MetaLamp_dXh0LxbfZxo/Front-end_su74P#_lu4Cc

Значения не подстраивались, была проблема с синхронизацией конфига слайдера и панели, точнее синхронизации вообще не было :)
