### ISSUE TITLE
Недочеты кода

### ISSUE THREAD

**Issue by sodiqit** [wendivue/range-slider#5]
вот от этой штуки лучше избавиться 
![image](https://user-images.githubusercontent.com/47000555/119222987-7747d800-bb10-11eb-878a-15b91f4410f8.png)
создай 2 типа, один PartialConfig, в котором все значения опциональные, а другой просто Config в котором будут все поля обязательны, и когда инициализируется слайдер, объединять дефолтный конфиг и значения, которые были переданы, валидацию нужно убрать в одно какое то место, а не размазывать по всем слоям

**Comment by sodiqit** [comment]
![image](https://user-images.githubusercontent.com/47000555/119223081-db6a9c00-bb10-11eb-93e8-4b4191d0da52.png)
конфиг должен быть приватным полем, к нему может иметь доступ только модель

**Comment by sodiqit** [comment]
зачем создавать публичное поле options?
![image](https://user-images.githubusercontent.com/47000555/119895762-95ba3300-bf57-11eb-85aa-cf54c36ce584.png)
если у тебя уже есть приватное конфиг

**Comment by sodiqit** [comment]
Опиши интерфейсы своих классов, сейчас их нет

**Comment by sodiqit** [comment]
Все клики, события должны обрабатываться вьюхой, презентер ничего не должен об этом знать

**Comment by sodiqit** [comment]
все это приватное должно быть)
![image](https://user-images.githubusercontent.com/47000555/119896519-91dae080-bf58-11eb-8334-60507ed42b04.png)

**Comment by sodiqit** [comment]
в классах должны сначала идти публичные методы, а в конце приватные

**Comment by sodiqit** [comment]
Presenter все-равно слишком жирный, там не нужны нижние 5 методов минимум, по клику на вьюху просто посылается сигнал о том, что нужно передать координаты в модель, а сейчас тут происходит некая валидация и лишняя логика, которой быть не должно. Также еще нет интерфейса для Presenter'a. Посмотри на паттерн наблюдатель он может помочь здесь

**Comment by sodiqit** [comment]
API лучше сделать по-другому, чтобы функция с плагином возвращала instance плагина, и через публичные методы можно было получать/менять настройки, подписываться на изменения и тд

**Comment by sodiqit** [comment]
вот такие бессмысленные имена лучше избегать, что значит typeData, что за данные типа там лежат? и типы должны начинаться с большой буквы, а интерефесы с префикса I
![image](https://user-images.githubusercontent.com/47000555/120099134-51938200-c153-11eb-82a9-4a066b59cdb9.png)

**Comment by wendivue** [comment]
> API лучше сделать по-другому, чтобы функция с плагином возвращала instance плагина, и через публичные методы можно было получать/менять настройки, подписываться на изменения и тд

`$(sliderId).rangeSlider({}).reset();`
`$(sliderId).rangeSlider({}).update({from: 10});`
Вот так?

**Comment by sodiqit** [comment]
> > API лучше сделать по-другому, чтобы функция с плагином возвращала instance плагина, и через публичные методы можно было получать/менять настройки, подписываться на изменения и тд
> 
> `$(sliderId).rangeSlider({}).reset();`
> `$(sliderId).rangeSlider({}).update({from: 10});`
> Вот так?

да, чтобы я мог записать плагин в переменную наподобие 
```js
const slider = $(sliderId).rangeSlider(options);
slider.update();
slider.get() // и тд
```

**Comment by sodiqit** [comment]
Лучше не используй Function, не советуют этого делать, лучше опиши свой тип функции
![image](https://user-images.githubusercontent.com/47000555/120855458-efde7800-c597-11eb-9c04-f7c7b0013c0a.png)

**Comment by sodiqit** [comment]
Не нужно писать тип когда он и так ts'ом выводится, у тебя array имеет тип Array<number>, поэтому и так ясно, что это number
![image](https://user-images.githubusercontent.com/47000555/120855761-56639600-c598-11eb-9d43-67312b31d2fa.png)

**Comment by sodiqit** [comment]
Presenter не должен апдейтить вьюху) когда я писал про ненужные методы, я не точное количество назвал)

**Comment by sodiqit** [comment]
Порефактори плз свои вложенные if'ы, в 90% случаев можно сделать более плоскую структуру
И избавься от таких конструкций, тут можно просто написать 
```ts
 if (elementType === MAX) {
      element = this.rangeMax;
    } 
    if (elementType === MIN) {
      element = this.rangeMin;
    }
```
![image](https://user-images.githubusercontent.com/47000555/120857763-341f4780-c59b-11eb-9276-9c0d5b3b5be6.png)

**Comment by sodiqit** [comment]
избавься от магических чисел, занеси их в константы)
![image](https://user-images.githubusercontent.com/47000555/120857920-70eb3e80-c59b-11eb-92be-ad7c6c9e64b4.png)
Прогляди по всему проекту

**Comment by sodiqit** [comment]
Посмотри на Pointer events, они имеют универсальный тип, чтобы не морочить себе голову с работой с разными интерфейсами
![image](https://user-images.githubusercontent.com/47000555/120858181-dccda700-c59b-11eb-87b0-e001dce9e152.png)

**Comment by sodiqit** [comment]
Вот так делать нельзя, bind возвращает новую функцию и при необходимости нельзя будет отвязать слушатель, посмотри в сторону плагина autobind
![image](https://user-images.githubusercontent.com/47000555/120858294-0555a100-c59c-11eb-9f44-adbc79c775ff.png)

**Comment by sodiqit** [comment]
Зачем тут переменная element нужна?
![image](https://user-images.githubusercontent.com/47000555/120859689-02f44680-c59e-11eb-89f5-ca274a151073.png)

**Comment by sodiqit** [comment]
от таких type assertions нужно избавиться querySelector может принимать дженерик с нужным типом. А так ты маскируешь потенциальные проблемы своего кода
![image](https://user-images.githubusercontent.com/47000555/120860072-90379b00-c59e-11eb-9a83-5a0797e44fa1.png)
![image](https://user-images.githubusercontent.com/47000555/120860292-dee53500-c59e-11eb-97cf-729073c9ecff.png)

**Comment by wendivue** [comment]
> Зачем тут переменная element нужна?
target - это элемент scale
element - это scale__item (фокус на отдельную ячейку)

**Comment by wendivue** [comment]
> Посмотри на Pointer events, они имеют универсальный тип, чтобы не морочить себе голову с работой с разными интерфейсами

Не очень подходит здесь

![Screenshot from 2021-06-06 17-41-46](https://user-images.githubusercontent.com/23695919/120917785-7a3bee80-c6f4-11eb-8752-edec7fd8be41.png)
![Screenshot from 2021-06-06 17-49-11](https://user-images.githubusercontent.com/23695919/120917787-7c05b200-c6f4-11eb-8b44-3ee468d5aef3.png)

**Comment by sodiqit** [comment]
> > Посмотри на Pointer events, они имеют универсальный тип, чтобы не морочить себе голову с работой с разными интерфейсами
> 
> Не очень подходит здесь
> 
> ![Screenshot from 2021-06-06 17-41-46](https://user-images.githubusercontent.com/23695919/120917785-7a3bee80-c6f4-11eb-8752-edec7fd8be41.png)
> ![Screenshot from 2021-06-06 17-49-11](https://user-images.githubusercontent.com/23695919/120917787-7c05b200-c6f4-11eb-8b44-3ee468d5aef3.png)
> 

Изучи его интерфейс, у него нет вообще поля touches, он расширяет интерфейс mouse event, но добавляет поддержку других способов ввода, touch, перо стилус и тд

**Comment by sodiqit** [comment]
type assertions
![image](https://user-images.githubusercontent.com/47000555/121772037-6d077f80-cb8c-11eb-8b26-129091a9415d.png)

**Comment by sodiqit** [comment]
![image](https://user-images.githubusercontent.com/47000555/121772764-f9b43c80-cb90-11eb-8327-4fb2488f3d41.png)

**Comment by sodiqit** [comment]
не очень понятно еще название метода checkElementType, по названию он должен проверять тип элемента, а по факту там проводиться валидация, тогда уж лучше validationElementType

**Comment by sodiqit** [comment]
дублируешь код, ты же вынес в отдельные интерфейсы subView свои
![image](https://user-images.githubusercontent.com/47000555/121773086-046fd100-cb93-11eb-8c67-2c63eda8b180.png)

**Comment by sodiqit** [comment]
![image](https://user-images.githubusercontent.com/47000555/121773150-6b8d8580-cb93-11eb-932a-62cf021a4cb9.png)
