### ISSUE TITLE
Синхронизация панели со слайдером

### ISSUE THREAD

**Issue by kate-fsd** [wendivue/range-slider#9]
![Peek 2021-09-17 19-43](https://user-images.githubusercontent.com/66846004/133824385-ee78c93f-c3b6-4d6f-8bf5-5c0725ef917b.gif)

Панель должна полностью соответствовать состоянию слайдера. Схема такая 
- вводишь новое значение в поле 
- передаешь его в слайдер 
- проводишь валидацию 
- устанавливаешь новые валидные значения в состояние
- оповещаешь внешних слушателей (которым является панель), что состояние изменилось, передаешь новые значения
- устанавливаешь эти новые значения в панель

**Comment by kate-fsd** [comment]
![image](https://user-images.githubusercontent.com/66846004/136100216-fe10df06-073a-4591-94ab-d9355230f075.png)

бегунок на 50, а он там быть не может

**Comment by kate-fsd** [comment]
![Peek 2021-10-05 23-49](https://user-images.githubusercontent.com/66846004/136100521-fad6a92e-2841-4237-a4c8-f8ac3ba6af99.gif)

Просто добавление второго бегунка не должно стереть мои предыдущие значения

**Comment by kate-fsd** [comment]
При вводе невалидных значении, выводи сообщение об ошибке, можно в консоли

**Comment by wendivue** [comment]
> Не могу поставить на 8

Да, логика в том чтобы шаг не был больше половины всей шкалы. Это будет довольна раздражающая для пользователя, когда шкала идет почти вконец при одном движении (и там остаеться 2 пиксель до конца), это особенно видно при значениях выше тысячи.

**Comment by wendivue** [comment]
> Еще обрати внимание, что перетаскивание бегунка не по центру диапазона

Я специально так сделал. Значения делят шкалу пополам, пользователю не нужно попадать точно в цель) Что добавляет удобства

Примерно так

![Group 1](https://user-images.githubusercontent.com/23695919/136104042-8f59200f-52ed-4fe2-9cbb-2e5c6b5f9cff.png)

**Comment by wendivue** [comment]
> Еще обрати внимание, что перетаскивание бегунка не по центру диапазона

а понял. Там стоит шаг на 8. У тебя не последняя версия, обнови, пожалуйста)

> Просто добавление второго бегунка не должно стереть мои предыдущие значения

с этим также, должно работать)

**Comment by kate-fsd** [comment]
> Да, логика в том чтобы шаг не был больше половины всей шкалы. Это будет довольна раздражающая для пользователя

Лучше это правило убрать. Его нет в задаче, насчет удобства пользователя - вопрос спорный, может это как раз ожидаемо, что шаг может быть больше половины шкалы. Зато в задаче есть пункт про последнее деление шкалы, которое может быть не равным шагу

**Comment by kate-fsd** [comment]
> бегунок на 50, а он там быть не может

вынесла в отдельный ишью #14
